name = "createpak"
author = "ldez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b76afccf923c959d5411ce51d8837304ee5ab5231ca638814ec2ad66340e6e6"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
