name: Packwiz Export and Release

on:
  push:
    branches:
      - main  # Trigger when there is a push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change to windows-latest if needed
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go (1.19+)
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'  # Ensure you use Go 1.19 or newer

      - name: Install Packwiz via Go
        run: |
          go install github.com/packwiz/packwiz@latest
          # Ensure that the packwiz binary is in your PATH
          echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Run Packwiz export (curseforge)
        run: |
          # The modpack is located at the root of the repository, no need to change the directory
          packwiz curseforge export

      - name: Run Packwiz export (modrinth)
        run: |
          # The modpack is located at the root of the repository, no need to change the directory
          packwiz modrinth export

      - name: List files after export
        run: ls -alh  # Check if the ZIP file exists

      - name: Create a new tag
        id: create_tag
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TAG_NAME="v${COMMIT_HASH}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV  # Store the tag in the environment for later steps

      - name: Create GitHub Release and Upload Files
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/*.zip
            ${{ github.workspace }}/*.mrpack
          tag_name: ${{ env.TAG_NAME }}  # Use the tag name from the environment variable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
