name: Packwiz Export and Release

on:
  push:
    branches:
      - main  # Trigger when there is a push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change to windows-latest if needed
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go (1.19+)
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'  # Ensure you use Go 1.19 or newer

      - name: Install Packwiz via Go
        run: |
          go install github.com/packwiz/packwiz@latest
          # Ensure that the packwiz binary is in your PATH
          echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Run Packwiz export
        run: |
          # The modpack is located at the root of the repository, no need to change the directory
          packwiz curseforge export

      - name: List files after export
        run: ls -alh  # Check if the ZIP file exists

      - name: Create GitHub Release and Upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
